routes/backend.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\SectionController;
use App\Http\Controllers\Dashboard\DoctorController;
use App\Http\Controllers\Dashboard\SingleServiceController;
use App\Http\Controllers\Dashboard\InsuranceController;
use App\Http\Controllers\Dashboard\AmbulanceController;
use App\Http\Livewire\CreateGroupServices;
use App\Http\Controllers\Dashboard\PatientController;

use App\Http\Controllers\Dashboard\ReceiptAccountController;

use App\Http\Controllers\Dashboard\PaymentAccountController;

Route::get('/Dashboard_Admin',[DashboardController::class,'index']);

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){


    //##################### Dashboard User ####################################
    Route::get('/dashboard/user', function () {
        return view('Dashboard.User.index');
    })->middleware(['auth'])->name('dashboard.user');
    //##########################################################################
    //##################### Dashboard Admin ####################################
    Route::get('/dashboard/admin', function () {
        return view('Dashboard.Admin.index');
    })->middleware(['auth:admin'])->name('dashboard.admin');

    //#############################################################################


    //##################### Dashboard Admin ####################################
    Route::get('/dashboard/doctor', function () {
        return view('Dashboard.Doctor.index');
    })->middleware(['auth:doctor'])->name('dashboard.doctor');

    //#############################################################################





    Route::middleware(['auth:admin'])->group(function (){
        //------------------------Section--------------------------------------------
        Route::resource('sections',SectionController::class);
        //----------------------------------------------------------------------------
        //------------------------Doctor-----------------------------------------------------------------------------------
        Route::resource('doctors',DoctorController::class);
        Route::post('update_password', [DoctorController::class, 'update_password'])->name('update_password');
        Route::post('update_status', [DoctorController::class, 'update_status'])->name('update_status');
        //----------------------------------------------------------------------------------------------------------------

        //------------------------Service-----------------------------------------------------------------------------------
        Route::resource('service', SingleServiceController::class);

        //----------------------------------------------------------------------------------------------------------------

        //------------------------------------GroupServices---------------------------------------------------------------
        Route::view('Add_GroupServices','livewire.GroupServices.include_create')->name('Add_GroupServices');
        //------------------------------------------------------------------------------------------------------------------



        //############################# insurance route ##########################################

        Route::resource('insurances', InsuranceController::class);

        //############################# end insurance route ######################################


        //############################# Ambulance route ##########################################

        Route::resource('ambulances', AmbulanceController::class);

        //############################# end insurance route ######################################


        //############################# Patient route ##########################################

        Route::resource('patients', PatientController::class);

        //############################# end insurance route ######################################



        //############################# single_invoices route ##########################################

        Route::view('single_invoices','livewire.single_invoices.index')->name('single_invoices');
        Route::view('print_single_invoices','livewire.single_invoices.print')->name('print_single_invoices');

        //############################# end single_invoices route ######################################







        //############################# Receipt route ##########################################

        Route::resource('receipts', ReceiptAccountController::class);

        //############################# end Receipt route ######################################


        //############################# Payment route ##########################################

      Route::resource('payments', PaymentAccountController::class);

        //############################# end Payment route ######################################



        //############################# group_invoices route ##########################################

        Route::view('group_invoices','livewire.group_invoices.index')->name('group_invoices');

        Route::view('group_print_single_invoices','livewire.group_invoices.print')->name('group_print_single_invoices');

        //############################# end single_invoices route ######################################




    });
    //-------------------------------------------------------------------------------


    require __DIR__.'/auth.php';

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Insurance.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Insurance extends Model  implements TranslatableContract
{
    use  Translatable;
    public $translatedAttributes=['name','notes'];
    protected  $guarded=[];
    use HasFactory;
}

app/Http/Controllers/Dashboard/AmbulanceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Interfaces\Ambulances\AmbulanceRepositoryInterface;

class AmbulanceController extends Controller
{
    private $ambulance;

    public function __construct(AmbulanceRepositoryInterface $ambulance)
    {
        $this->ambulance = $ambulance;
    }

    public function index()
    {
        return  $this->ambulance->index();
    }

    public function create()
    {
        return  $this->ambulance->create();
    }


    public function store(Request $request)
    {
        return  $this->ambulance->store($request);
    }

    public function edit($id)
    {
        return  $this->ambulance->edit($id);
    }


    public function update(Request $request)
    {
        return $this->ambulance->update($request);
    }



    public function destroy(Request $request)
    {
        return $this->ambulance->destroy($request);
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public  function index(){
        return view('Dashboard.index');
    }
}

app/Http/Controllers/Dashboard/DoctorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Doctors\DoctorRepositoryInterface;
use App\Models\Doctor;
use App\Models\Section;
use Illuminate\Http\Request;

class DoctorController extends Controller
{

    private $Doctors;

    public function __construct(DoctorRepositoryInterface $Doctors)
    {
        $this->Doctors = $Doctors;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->Doctors->index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->Doctors->create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->Doctors->store($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->Doctors->edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $this->Doctors->update($request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
       return $this->Doctors->destroy($request);
    }

    public function update_password(Request $request)
    {
      //  return $request->all();
        $this->validate($request, [
            'password' => 'required|min:6|confirmed',
            'password_confirmation' => 'required|min:6'
        ]);

        return $this->Doctors->update_password($request);
    }

    public function update_status(Request $request)
    {
        $this->validate($request, [
            'status' => 'required|in:0,1',
        ]);
        return $this->Doctors->update_status($request);
    }
}

app/Http/Controllers/Dashboard/InsuranceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Interfaces\Insurances\InsuranceRepositoryInterface;

class InsuranceController extends Controller
{
    private $insurance;

    public function __construct(InsuranceRepositoryInterface $insurance)
    {
        $this->insurance = $insurance;
    }

    public function index()
    {
        return $this->insurance->index();
    }

    public function create()
    {
        return $this->insurance->create();
    }


    public function store(Request $request)
    {
        return $this->insurance->store($request);
    }

    public function edit($id)
    {
        return $this->insurance->edit($id);
    }


    public function update(Request $request)
    {
        return $this->insurance->update($request);
    }



    public function destroy(Request $request)
    {
        return $this->insurance->destroy($request);
    }

}

app/Http/Controllers/Dashboard/PatientController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Interfaces\Patients\PatientRepositoryInterface;

class PatientController extends Controller
{
    private $patient;

    public function __construct(PatientRepositoryInterface $patient)
    {
        $this->patient = $patient;
    }

    public function index()
    {
        return  $this->patient->index();
    }

    public function create()
    {
        return  $this->patient->create();
    }


    public function store(Request $request)
    {
        return  $this->patient->store($request);
    }

    public function edit($id)
    {
        return  $this->patient->edit($id);
    }

    public function show($id)
    {
        return  $this->patient->show($id);
    }


    public function update(Request $request)
    {
        return  $this->patient->update($request);
    }



    public function destroy(Request $request)
    {
        return  $this->patient->destroy($request);
    }

}

app/Http/Controllers/Dashboard/PaymentAccountController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Finance\PaymentRepositoryInterface;
use Illuminate\Http\Request;

class PaymentAccountController extends Controller
{
    private $payment;

    public function __construct(PaymentRepositoryInterface $payment)
    {
        $this->payment = $payment;
    }


    public function index()
    {
        return  $this->payment->index();
    }

    public function create()
    {
        return  $this->payment->create();
    }


    public function store(Request $request)
    {
        return  $this->payment->store($request);
    }


    public function show($id)
    {
        return  $this->payment->show($id);
    }


    public function edit($id)
    {
        return  $this->payment->edit($id);
    }


    public function update(Request $request)
    {
        return  $this->payment->update($request);
    }


    public function destroy(Request $request)
    {
        return  $this->payment->destroy($request);
    }



}

app/Http/Controllers/Dashboard/ReceiptAccountController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Finance\ReceiptRepositoryInterface;
use Illuminate\Http\Request;

class ReceiptAccountController extends Controller
{
    private $receipt;

    public function __construct(ReceiptRepositoryInterface $receipt)
    {
        $this->receipt = $receipt;
    }


    public function index()
    {
        return  $this->receipt->index();
    }

    public function create()
    {
        return  $this->receipt->create();
    }


    public function store(Request $request)
    {
        return  $this->receipt->store($request);
    }


    public function show($id)
    {
        return  $this->receipt->show($id);
    }


    public function edit($id)
    {
        return  $this->receipt->edit($id);
    }


    public function update(Request $request)
    {
        return  $this->receipt->update($request);
    }


    public function destroy(Request $request)
    {
        return  $this->receipt->destroy($request);
    }
}

app/Http/Controllers/Dashboard/SectionController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Sections\SectionRepositoryInterface;
use Illuminate\Http\Request;

class SectionController extends Controller
{
    private $sections;
    public function __construct(SectionRepositoryInterface    $sections )
    {
         $this->sections=$sections;
    }
    public function index()
    {
        return $this->sections->index();
    }
    public function show($id)
    {
        return $this->sections->show($id);
    }
    public function store(Request $request)
    {
        return $this->sections->store($request);
    }
    public function update(Request $request)
    {
        return $this->sections->update($request);
    }
    public function destroy(Request $request)
    {
        return $this->sections->destroy($request);
    }
}

app/Http/Controllers/Dashboard/SingleServiceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Services\SingleServices\SingleServiceRepositoryInterface;
use Illuminate\Http\Request;

class SingleServiceController extends Controller
{    private $services;
    public function __construct(SingleServiceRepositoryInterface    $services )
    {
        $this->services=$services;
    }
    public function index()
    {
        return   $this->services->index();
    }

    public function store(Request $request)
    {
        return   $this->services->store($request);
    }
    public function update(Request $request)
    {
        return   $this->services->update($request);
    }
    public function destroy(Request $request)
    {
        return   $this->services->destroy($request);
    }
}

resources/views/Dashboard/insurances/create.blade.php
@extends('Dashboard.layouts.master')
@section('css')
    <!--Internal   Notify -->
    <link href="{{URL::asset('dashboard/plugins/notify/css/notifIt.css')}}" rel="stylesheet"/>
@endsection
@section('title')
    {{trans('insurance.add_insurance')}}
@endsection
@section('page-header')
<!-- breadcrumb -->
<div class="breadcrumb-header justify-content-between">
    <div class="my-auto">
        <div class="d-flex">
            <h4 class="content-title mb-0 my-auto">جميع الخدمات</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ {{trans('insurance.Insurance')}}</span>
        </div>
    </div>
</div>
<!-- breadcrumb -->
@endsection
@section('content')
@include('Dashboard.messages_alert')
<!-- row -->
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form action="{{route('insurances.store')}}" method="post" autocomplete="off">
                    @csrf

                        @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties )
                            <div class="form-group">
                                <label>{{trans('insurance.' . $localeCode . '.name')}}</label>
                                <input type="text" name="{{ $localeCode }}[name]" class="form-control" value="{{ old($localeCode . '.name') }}">
                            </div>
                        @endforeach

                    <div class="row">
                        <div class="col">
                            <label>{{trans('insurance.conpany_code')}}</label>
                            <input type="text" name="insurance_code"  value="{{old('insurance_code')}}" class="form-control @error('insurance_code') is-invalid @enderror">
                            @error('insurance_code')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>



                    </div>

                    <br>

                    <div class="row">
                        <div class="col">
                            <label>{{trans('insurance.discount_percentage')}} %</label>
                            <input type="number" name="discount_percentage" class="form-control @error ('discount_percentage') is-invalid @enderror">
                            @error('discount_percentage')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="col">
                            <label>{{trans('insurance.insurance_bearing_percentage')}} %</label>
                            <input type="number" name="Company_rate" class="form-control @error ('Company_rate') is-invalid @enderror">
                            @error('Company_rate')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                    </div>

                    <br>

                    @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties )
                        <div class="form-group">
                            <label>{{trans('insurance.' . $localeCode . '.notes')}}</label>
                            <textarea  name="{{ $localeCode }}[notes]" class="form-control" >{{old($localeCode . '.notes')}} </textarea>
                        </div>
                    @endforeach

                    <br>

                    <div class="row">
                        <div class="col">
                            <button class="btn btn-success">{{trans('insurance.save')}}</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- row closed -->
@endsection
@section('js')
    <script src="{{URL::asset('dashboard/plugins/notify/js/notifIt.js')}}"></script>
    <script src="{{URL::asset('/plugins/notify/js/notifit-custom.js')}}"></script>
@endsection

resources/views/Dashboard/insurances/delete.blade.php
<!-- Deleted insurance -->
<div class="modal fade" id="delete{{$insurance->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{trans('insurance.delete')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{route('insurances.destroy','test')}}" method="post">
                    @method('DELETE')
                    @csrf

                    {{-- input hidden value => id   --}}
                    <input type="hidden" name="id" value="{{$insurance->id}}">

                    <div class="row">
                        <div class="col">
                            <p class="h5 text-danger">{{trans('insurance.Deleted')}}</p>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{trans('insurance.close')}}</button>
                        <button class="btn btn-success">{{trans('insurance.save')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/Dashboard/insurances/edit.blade.php
@extends('Dashboard.layouts.master')
@section('css')

    <!--Internal   Notify -->
    <link href="{{ URL::asset('Admin/assets/plugins/notify/css/notifIt.css') }}" rel="stylesheet"/>
@endsection
@section('title')
    {{trans('insurance.edit_insurance')}}
@endsection
@section('page-header')
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div class="my-auto">
            <div class="d-flex">
                <h4 class="content-title mb-0 my-auto">{{trans('main-sidebar_trans.Services')}}</h4><span
                    class="text-muted mt-1 tx-13 mr-2 mb-0">/ {{trans('insurance.Insurance')}}</span>
            </div>
        </div>
    </div>
    <!-- breadcrumb -->
@endsection
@section('content')
    <!-- row -->
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">

                    <form action="{{route('insurances.update','test')}}" method="post">
                        @method('PUT')
                        @csrf

                        {{-- input hidden value => id   --}}
                        <input type="hidden" name="id" value="{{$insurance->id}}">

                        @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties )
                            <div class="form-group">
                                <label>{{trans('insurance.' . $localeCode . '.name')}}</label>
                                <input type="text" name="{{ $localeCode }}[name]" class="form-control" value="{{  $insurance->translateOrNew($localeCode)->name }}">
                            </div>
                        @endforeach



                        <div class="row">

                            <div class="col">
                                <label>{{trans('insurance.conpany_code')}}</label>
                                <input type="text" name="insurance_code" value="{{$insurance->insurance_code}}"
                                       class="form-control @error('insurance_code') is-invalid @enderror">
                                @error('insurance_code')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                         {{--    <div class="col">
                                <label>{{trans('insurance.Company_name')}}</label>
                                <input type="text" name="name" value="{{$insurance->name}}"
                                       class="form-control @error('name') is-invalid @enderror">
                                @error('name')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>--}}

                        </div>

                        <br>

                        <div class="row">

                            <div class="col">
                                <label>{{trans('insurance.discount_percentage')}} %</label>
                                <input type="number" name="discount_percentage" value="{{$insurance->discount_percentage}}"
                                       class="form-control @error ('discount_percentage') is-invalid @enderror">
                                @error('discount_percentage')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="col">
                                <label>{{trans('insurance.insurance_bearing_percentage')}} %</label>
                                <input type="number" name="Company_rate"
                                    value="{{$insurance->Company_rate}}"  class="form-control @error ('Company_rate') is-invalid @enderror">
                                @error('Company_rate')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        <br>

                        @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties )
                            <div class="form-group">
                                <label>{{trans('insurance.' . $localeCode . '.notes')}}</label>
                                <input type="text" name="{{ $localeCode }}[notes]" class="form-control" value="{{  $insurance->translateOrNew($localeCode)->notes }}">
                            </div>
                        @endforeach

                        <br>

                        <div class="row">
                            <div class="col">
                                <label>حالة التفعيل</label>
                                 &nbsp;
                                <input name="status" {{$insurance->status == 1 ? 'checked' : ''}} value="1" type="checkbox" class="form-check-input" id="exampleCheck1">
                            </div>
                        </div>

                        <br>

                        <div class="row">
                            <div class="col">
                                <button class="btn btn-success">{{trans('insurance.save')}}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- row closed -->
@endsection
@section('js')
    <!--Internal  Notify js -->
    <script src="{{URL::asset('Admin/assets/plugins/notify/js/notifIt.js')}}"></script>
    <script src="{{URL::asset('Admin/assets/plugins/notify/js/notifit-custom.js')}}"></script>
@endsection

resources/views/Dashboard/insurances/index.blade.php
@extends('Dashboard.layouts.master')
@section('css')
<!--Internal   Notify -->
<link href="{{URL::asset('dashboard/plugins/notify/css/notifIt.css')}}" rel="stylesheet"/>
@endsection
@section('title')
    {{trans('main-sidebar_trans.Insurance')}}
@endsection
@section('page-header')
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div class="my-auto">
            <div class="d-flex">
                <h4 class="content-title mb-0 my-auto">{{trans('main-sidebar_trans.Services')}}</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ {{trans('main-sidebar_trans.Insurance')}}</span>
            </div>
        </div>
    </div>
    <!-- breadcrumb -->
@endsection
@section('content')

@include('Dashboard.messages_alert')

    <!-- row -->
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <a href="{{route('insurances.create')}}" class="btn btn-primary">{{trans('insurance.add_insurance')}}</a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table text-md-nowrap text-center" id="example1">
                            <thead>
                            <tr class="table-secondary">
                                <th>#</th>
                                <th >{{trans('insurance.company_name')}}</th>
                                <th >{{trans('insurance.conpany_code')}}</th>
                                <th >{{trans('insurance.discount_percentage')}}</th>
                                <th >{{trans('insurance.insurance_bearing_percentage')}}</th>
                                <th >{{trans('insurance.status')}}</th>
                                <th >{{trans('insurance.notes')}}</th>
                                <th >{{trans('insurance.processes')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($insurances as $insurance)
                                <tr>
                                    <td>{{$loop->iteration }}</td>
                                    <td>{{$insurance->insurance_code}}</td>
                                    <td>{{$insurance->name}}</td>
                                    <td>{{$insurance->discount_percentage}}</td>
                                    <td>{{$insurance->Company_rate}}</td>
                                    <td class="{{$insurance->status == 1 ? 'bg-success':'bg-danger'}}">{{$insurance->status == 1 ? 'مفعل' : 'غير مفعل'}}</td>
                                    <td>{{$insurance->notes}}</td>
                                    <td>
                                        <a href="{{route('insurances.edit',$insurance->id)}}" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>
                                        <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete{{$insurance->id}}"><i class="fas fa-trash"></i>
                                        </button>

                                    </td>
                                 @include('Dashboard.insurances.delete')
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- row closed -->
@endsection
@section('js')

    <!--Internal  Notify js -->
    <script src="{{URL::asset('dashboard/plugins/notify/js/notifIt.js')}}"></script>
    <script src="{{URL::asset('/plugins/notify/js/notifit-custom.js')}}"></script>

@endsection